import { useEffect, useState } from "react";
const endpoint = "http://localhost:5000/api/employees";
export default function EmployeesPage() {
  const [employees, setEmployees] = useState([]); const [form, setForm] = useState({ name: "", phone: "", role: "" }); const [message, setMessage] = useState("");
  const load = async () => { try { const r = await fetch(endpoint); setEmployees(await r.json()); } catch { setMessage("Could not load employees."); } };
  useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); const r = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await r.json(); if (!r.ok) { setMessage(data.message || "Could not add employee."); return; } setForm({ name: "", phone: "", role: "" }); setMessage("Employee added."); load(); };
  const remove = async (id) => { if (!window.confirm("Remove this employee?")) return; await fetch(`${endpoint}/${id}`, { method: "DELETE" }); load(); };
  return <section className="management-page"><p className="eyebrow">Team</p><h1>Employees</h1><p>Add team members who deliver your events.</p><div className="management-grid"><form className="management-card" onSubmit={submit}><h2>Add employee</h2>{message && <p className="form-message">{message}</p>}<label>Name</label><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><label>Mobile number</label><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><label>Role</label><input value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} placeholder="Decorator, manager, driver" required /><button className="button" type="submit">Add employee</button></form><section className="management-card"><h2>Team members</h2>{employees.length === 0 ? <p>No employees added yet.</p> : <div className="employee-list">{employees.map((employee) => <article key={employee._id}><div><strong>{employee.name}</strong><span>{employee.role}{employee.phone ? ` · ${employee.phone}` : ""}</span></div><button className="button button-secondary" onClick={() => remove(employee._id)}>Remove</button></article>)}</div>}</section></div></section>;
}
